version: '3.8'

services:
  bookreviews:
    image: bookreviews
    container_name: bookreviews
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: sh -c 'python3 manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn --bind 0.0.0.0:8000 project_config.wsgi'
    depends_on:
      pgdb:
        condition: service_healthy
    volumes:
      - static_files:/app/static/
    expose:
      - 8000
    env_file:
      - ./django/.env.dev

  pgdb:
    image: postgres
    container_name: pgdb
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    env_file:
      - ./postgres/.env.dev
    volumes:
       - ./postgres/db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
  
  nginx:
    image: nginx 
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - bookreviews
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - static_files:/static/

volumes:
  static_files: